[package]
edition = "2021"
name = "command"
version = "0.1.0"

[[bin]]
name = "command"
path = "main.rs"

[dependencies]
anyhow = {version = "1.0.62"}
cursive = {version = "0.19", default-features = false, features = ["termion-backend"]}
